// ══════════════════════════════════════════════
// data.js — Product & Bundle Data
// ══════════════════════════════════════════════

const PRODUCTS = [
  {
    id: 1,
    name: "Landing Page UI Kit",
    price: 12,
    desc: "Modern UI kit for landing pages and startups. Includes 40+ components.",
    cat: "UI Kits",
    icon: "lightning",
    ibg: "rgba(124,111,247,0.15)",
    ic: "#a5a0ff",
    badge: "popular",
    tags: ["Figma", "40+ Screens"],
  },
  {
    id: 2,
    name: "Portfolio Template",
    price: 18,
    desc: "Responsive portfolio template built for developers who want to stand out.",
    cat: "Templates",
    icon: "briefcase",
    ibg: "rgba(52,211,153,0.12)",
    ic: "#34d399",
    badge: "new",
    tags: ["HTML/CSS", "Dark Mode"],
  },
  {
    id: 3,
    name: "Admin Dashboard UI",
    price: 25,
    desc: "Clean, data-rich admin design system with charts, tables and forms.",
    cat: "UI Kits",
    icon: "chart",
    ibg: "rgba(251,146,60,0.12)",
    ic: "#fb923c",
    badge: null,
    tags: ["React", "Charts"],
  },
  {
    id: 4,
    name: "Mobile App UI Pack",
    price: 15,
    desc: "Reusable mobile components for iOS and Android app interfaces.",
    cat: "UI Kits",
    icon: "mobile",
    ibg: "rgba(248,113,113,0.12)",
    ic: "#f87171",
    badge: "sale",
    tags: ["Swift", "Kotlin"],
  },
  {
    id: 5,
    name: "Icon Pack (500 icons)",
    price: 8,
    desc: "Minimal, consistent icon set in SVG and PNG — perfect for any project.",
    cat: "Icons",
    icon: "grid",
    ibg: "rgba(192,132,252,0.12)",
    ic: "#c084fc",
    badge: null,
    tags: ["SVG", "PNG", "500 icons"],
  },
  {
    id: 6,
    name: "SaaS Landing Kit",
    price: 22,
    desc: "Complete SaaS marketing site kit with hero, pricing, FAQ and more.",
    cat: "Templates",
    icon: "rocket",
    ibg: "rgba(56,189,248,0.12)",
    ic: "#38bdf8",
    badge: "new",
    tags: ["Tailwind", "10 Sections"],
  },
];

const CATEGORIES = ["All", "UI Kits", "Templates", "Icons"];

const BUNDLES = [
  {
    name: "UI Kits Bundle",
    desc: "All 3 UI Kits — Landing Page, Dashboard & Mobile",
    price: 42,
    orig: 52,
    icon: "lightning",
    ibg: "rgba(124,111,247,0.15)",
    ic: "#a5a0ff",
  },
  {
    name: "Templates Bundle",
    desc: "Portfolio + SaaS Landing Kit together",
    price: 32,
    orig: 40,
    icon: "rocket",
    ibg: "rgba(56,189,248,0.12)",
    ic: "#38bdf8",
  },
  {
    name: "Full Collection",
    desc: "Every product in PixelMarket — 6 assets total",
    price: 69,
    orig: 98,
    icon: "star",
    ibg: "rgba(251,191,36,0.12)",
    ic: "#fbbf24",
  },
];